### ISSUE TITLE
Bridging from/to the same domain ID

### ISSUE THREAD

**Issue by jacobperron** [ros2/domain_bridge#23]
I noticed a degenerate case if we configure a topic bridge from and to the same domain ID. In this case, we enter a feedback loop where the domain bridge subscribes to itself, resulting in the publication of many duplicate messages.

Here's a simple configuration that reproduces the issue:

```yaml
name: my_bridge
from_domain: 2
to_domain: 2
topics:
  chatter:
    type: std_msgs/msg/String
```

We can trigger a feedback loop by publishing a single message to the /chatter topic:

```
ROS_DOMAIN_ID=2 ros2 topic pub -1 /chatter std_msgs/msg/String "{data: 'hello'}"
```

And we can see a flood of messages on the /chatter topic:

```
ROS_DOMAIN_ID=2 ros2 topic echo /chatter
```

I think we should guard against this case. If a user tries to create a bridge with the same from/to domain ID, then log a warning and do not bridge the topic.
